site_name: membrane-toolkit Documentation
site_description: Documentation for membrane-toolkit, Python tools for membrane science.
copyright: Ryan Kingsbury

theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'deep orange'

nav:
  - Home: index.md
  - Installation: install.md
  - Getting Started: getting_started.md
  - Core Functions: 
      - Diffusion: core_functions/diffusion.md
      - Donnan Equilibrium: core_functions/donnan.md
      - Manning Theory: core_functions/manning.md
      - Electrochemical Properties: core_functions/potential.md
  - For Developers: develop.md

repo_url: https://github.com/rkingsbury/membrane-toolkit
site_url: https://rkingsbury.github.io/membrane-toolkit/
docs_dir: ./membrane_toolkit/docs
copyright: 2020 Ryan Kingsbury
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - mdx_math:
      enable_dollar_delimiter: True
      add_preview: True
  - toc:
      permalink: true

plugins:
  - search
  - minify
  - mkdocstrings:
      watch:
        - membrane_toolkit
      handlers:
        python:
          rendering:
            show_root_heading: yes

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js

