site_name: membrane-toolkit Documentation
site_description: Documentation for membrane-toolkit, Python tools for membrane science.
copyright: Ryan Kingsbury

theme:
  name: 'material'

nav:
  - Home: index.md
  - Core Functions: core_functions/core_functions.md

repo_url: https://github.com/rkingsbury/membrane-toolkit
site_url: https://membrane-toolkit.readthedocs.io
docs_dir: ./membrane_toolkit/docs
site_dir: ./docs
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - mdx_math:
      enable_dollar_delimiter: True
      add_preview: True
  - toc:
      permalink: true

plugins:
  - search
  - minify
  - mkdocstrings:
      watch:
        - membrane_toolkit

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js

